version: "3.8"

services:
  app:
    build: .
    container_name: python_app
    ports:
      - "5000:5000"
    environment:
      DB_USER: postgres
      DB_PASSWORD: GsWUnMeIInzKCeATVZctEQCnewxwCAFk
      DB_HOST: interchange.proxy.rlwy.net
      DB_PORT: 54776
      DB_NAME: teaching_db
    restart: always
